import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';
 
export const THEME = {
  light: {
    background: '#F4F7F3',
    foreground: '#15221D',
    card: '#FFFFFF',
    cardForeground: '#15221D',
    popover: '#FFFFFF',
    popoverForeground: '#15221D',
    primary: '#0F9D76',
    primaryForeground: '#F5FFFB',
    secondary: '#E8F1EC',
    secondaryForeground: '#173027',
    muted: '#ECF2EE',
    mutedForeground: '#5C746B',
    accent: '#D9F1E7',
    accentForeground: '#173027',
    destructive: '#D94E45',
    border: '#D3DFD8',
    input: '#FFFFFF',
    ring: '#0F9D76',
    radius: '0.875rem',
    chart1: '#0F9D76',
    chart2: '#1E88E5',
    chart3: '#EAB308',
    chart4: '#F59E0B',
    chart5: '#7C5CFA',
  },
  dark: {
    background: '#0D1512',
    foreground: '#EAF3EE',
    card: '#15201C',
    cardForeground: '#EAF3EE',
    popover: '#15201C',
    popoverForeground: '#EAF3EE',
    primary: '#3FD0A5',
    primaryForeground: '#0C1713',
    secondary: '#22312B',
    secondaryForeground: '#D9EAE2',
    muted: '#203029',
    mutedForeground: '#9BB8AD',
    accent: '#294137',
    accentForeground: '#EAF3EE',
    destructive: '#F16D63',
    border: '#32443D',
    input: '#1D2A24',
    ring: '#3FD0A5',
    radius: '0.875rem',
    chart1: '#3FD0A5',
    chart2: '#57A7FF',
    chart3: '#F2CC5D',
    chart4: '#F6B34C',
    chart5: '#A58BFF',
  },
};
 
export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
